### ISSUE TITLE
[BUG] Restrict the ability to upload photos to Google photos of GP$Tech

### ISSUE THREAD

**Issue by gabriela-becerra-jala** [gp4tech/website#111]
**Describe the bug**
The option of upload photos to Google Photos gallery of GP4Tech is available to anybody that has Google account. This can be a security gap if we don't control who is uploading photos to the Gallery.

**To Reproduce**
1. Go to 'https://photos.google.com/share/AF1QipPFFd_0dHtjnKi4z_zpHQBvhFet5gdkUAxBS6ul1NaoWwuaNQtLaZkrSnrwU0xX8Q?key=ek5kaDdhVl9uN0JEUnFTSXJNdHlrLWsza1ZjTjRR'
2. Click on 'Activity' option
![image](https://user-images.githubusercontent.com/3791746/60123863-6345a100-9756-11e9-84ee-d416633b21d3.png)

3. Copy a photo from anywhere in the Activity as a message (You must be logged with a valid google account to do this operation).
4. See that the photo is uploaded without restrictions or warning message.

**Current behavior**
Anyone with Google account can upload photos to our GP4Tech Google Photos gallery.

**Expected behavior**
A restricted group of people should have the ability to upload photos to GP4Tech Google Photos gallery.

**Comment by GigiEillen** [comment]
The option to upload photos in Google Photos gallery of GP4Tech is now not available to anybody that has Google account.
