### ISSUE TITLE
[BUG] Blank space displayed when rendering team members

### ISSUE THREAD

**Issue by gabriela-becerra-jala** [gp4tech/website#115]
**Describe the bug**
Strange blank space is displayed in the team members list on About-Us page.

**To Reproduce**
1. Go to 'https://gp4tech.com/about-us'
2. Scroll down unitl 'Ines Baina' 
4. See the blank space

**Current behavior**
Blank space is displayed at the left of "Ines Baina" card, that covers 3 spaces.

**Expected behavior**
No blank space should be when rendering the team members cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/3791746/60130796-f934f800-9765-11e9-9468-746d7a02c58d.png)

**Comment by dmeneses** [comment]
We changed image for one of the members that was the problem.
